// <auto-generated />
using System;
using CarPark.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarPark.Infra.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210125145042_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarPark.Dominio.PessoaFisicaContext.Entities.PessoaFisica", b =>
                {
                    b.Property<int>("PessoaFisicaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("Rg")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Sexo")
                        .HasColumnType("nchar(2)")
                        .IsFixedLength(true)
                        .HasMaxLength(2);

                    b.HasKey("PessoaFisicaId");

                    b.ToTable("PessoaFisica");
                });

            modelBuilder.Entity("CarPark.Dominio.PessoaJuridicaContext.Entities.PessoaJuridica", b =>
                {
                    b.Property<int>("PessoaJuridicaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CNPJ")
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("PessoaJuridicaId");

                    b.ToTable("PessoaJuridica");
                });

            modelBuilder.Entity("CarPark.Dominio.Shared.Entities.Email", b =>
                {
                    b.Property<int>("EmailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EnderecoEmail")
                        .HasColumnType("nvarchar(160)")
                        .HasMaxLength(160);

                    b.Property<int?>("PessoaFisicaId")
                        .HasColumnType("int");

                    b.Property<int?>("PessoaJuridicaId")
                        .HasColumnType("int");

                    b.HasKey("EmailId");

                    b.HasIndex("PessoaFisicaId");

                    b.HasIndex("PessoaJuridicaId");

                    b.ToTable("Email");
                });

            modelBuilder.Entity("CarPark.Dominio.Shared.Entities.Endereco", b =>
                {
                    b.Property<int>("EnderecoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("CEP")
                        .HasColumnType("nchar(8)")
                        .IsFixedLength(true)
                        .HasMaxLength(8);

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Estado")
                        .HasColumnType("nchar(2)")
                        .IsFixedLength(true)
                        .HasMaxLength(2);

                    b.Property<string>("Logradouro")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<int?>("PessoaFisicaId")
                        .HasColumnType("int");

                    b.Property<int?>("PessoaJuridicaId")
                        .HasColumnType("int");

                    b.HasKey("EnderecoId");

                    b.HasIndex("PessoaFisicaId")
                        .IsUnique()
                        .HasFilter("[PessoaFisicaId] IS NOT NULL");

                    b.HasIndex("PessoaJuridicaId")
                        .IsUnique()
                        .HasFilter("[PessoaJuridicaId] IS NOT NULL");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("CarPark.Dominio.Shared.Entities.Telefone", b =>
                {
                    b.Property<int>("TelefoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.Property<int?>("PessoaFisicaId")
                        .HasColumnType("int");

                    b.Property<int?>("PessoaJuridicaId")
                        .HasColumnType("int");

                    b.HasKey("TelefoneId");

                    b.HasIndex("PessoaFisicaId");

                    b.HasIndex("PessoaJuridicaId");

                    b.ToTable("Telefone");
                });

            modelBuilder.Entity("CarPark.Dominio.Shared.Entities.Email", b =>
                {
                    b.HasOne("CarPark.Dominio.PessoaFisicaContext.Entities.PessoaFisica", "PessoaFisica")
                        .WithMany("Emails")
                        .HasForeignKey("PessoaFisicaId");

                    b.HasOne("CarPark.Dominio.PessoaJuridicaContext.Entities.PessoaJuridica", "PessoaJuridica")
                        .WithMany("Emails")
                        .HasForeignKey("PessoaJuridicaId");
                });

            modelBuilder.Entity("CarPark.Dominio.Shared.Entities.Endereco", b =>
                {
                    b.HasOne("CarPark.Dominio.PessoaFisicaContext.Entities.PessoaFisica", "PessoaFisica")
                        .WithOne("Endereco")
                        .HasForeignKey("CarPark.Dominio.Shared.Entities.Endereco", "PessoaFisicaId");

                    b.HasOne("CarPark.Dominio.PessoaJuridicaContext.Entities.PessoaJuridica", "PessoaJuridica")
                        .WithOne("Endereco")
                        .HasForeignKey("CarPark.Dominio.Shared.Entities.Endereco", "PessoaJuridicaId");
                });

            modelBuilder.Entity("CarPark.Dominio.Shared.Entities.Telefone", b =>
                {
                    b.HasOne("CarPark.Dominio.PessoaFisicaContext.Entities.PessoaFisica", "PessoaFisica")
                        .WithMany("Telefones")
                        .HasForeignKey("PessoaFisicaId");

                    b.HasOne("CarPark.Dominio.PessoaJuridicaContext.Entities.PessoaJuridica", "PessoaJuridica")
                        .WithMany("Telefones")
                        .HasForeignKey("PessoaJuridicaId");
                });
#pragma warning restore 612, 618
        }
    }
}
